describe("log", function()
  describe("and_alert", function()
    it("should send message to the right logger", function()
      pending("...")
    end)
    it("should show an alert", function()
      pending("...")
    end)
  end)
end)
